spring:
  application:
    name: springtemplate
    id: com.sphirye.springtemplate
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
app:
  jwt:
    secret-key: ${APP_JWT_SECRET_KEY}
  security:
    cors:
      origins: ${APP_SECURITY_CORS_ORIGINS}
      methods: GET, PUT, PATCH, DELETE, HEAD

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tagsSorter: alpha
    operationsSorter: alpha
  api-docs:
    path: /api-docs
  show-actuator: true